name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install matplotlib
    - name: Test with pytest
      run: |
        pytest -s tests/test_Update_Stock.py
    - name: Upload graph as artifact
      uses: actions/upload-artifact@v3
      with:
        name: stock-graph
        path: stock_prices.png  # 그래프 파일 경로 (예시)
